### ISSUE TITLE
Lsp-bridge does not work on doom emacs

### ISSUE THREAD

**Issue by hhamud** [manateelazycat/lsp-bridge#931]
I have followed the installation instructions and have disabled company, eglot, lsp, etc but it still does not work.

```shell
user@192 ~ % pip install epc orjson sexpdata six setuptools paramiko rapidfuzz
Requirement already satisfied: epc in /opt/homebrew/lib/python3.10/site-packages (0.0.5)
Requirement already satisfied: orjson in /opt/homebrew/lib/python3.10/site-packages (3.10.2)
Requirement already satisfied: sexpdata in /opt/homebrew/lib/python3.10/site-packages (0.0.3)
Requirement already satisfied: six in /opt/homebrew/lib/python3.10/site-packages (1.16.0)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.10/site-packages (69.2.0)
Requirement already satisfied: paramiko in /opt/homebrew/lib/python3.10/site-packages (3.4.0)
Requirement already satisfied: rapidfuzz in /opt/homebrew/lib/python3.10/site-packages (3.8.1)
Requirement already satisfied: bcrypt>=3.2 in /opt/homebrew/lib/python3.10/site-packages (from paramiko) (4.1.2)
Requirement already satisfied: cryptography>=3.3 in /opt/homebrew/lib/python3.10/site-packages (from paramiko) (41.0.2)
Requirement already satisfied: pynacl>=1.5 in /opt/homebrew/lib/python3.10/site-packages (from paramiko) (1.5.0)
Requirement already satisfied: cffi>=1.12 in /opt/homebrew/lib/python3.10/site-packages (from cryptography>=3.3->paramiko) (1.15.1)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=3.3->paramiko) (2.21)
```

from the lsp-bridge logs

```shell
Process *lsp-bridge* exited abnormally with code 1
Traceback (most recent call last):
  File "/Users/user/.emacs.d/.local/straight/build-29.1/lsp-bridge/lsp_bridge.py", line 32, in <module>
    from epc.server import ThreadingEPCServer
ModuleNotFoundError: No module named 'epc'
```

**Comment by chookity-pokk** [comment]
@hhamud I am experiencing the same issue. Did you solve it? If so, how did you do it?

**Comment by hhamud** [comment]
> @hhamud I am experiencing the same issue. Did you solve it? If so, how did you do it?

it had nothing to do with the repo, it was just my python installation was borked. I fixed it by just using `pyenv` and `poetry` to install it onto my system. If that doesnt work then you could try just deleting your python and doing a clean re-install.

**Comment by chookity-pokk** [comment]
Unfortunately I can't get it to work with MacOS even when using [exec-path](https://github.com/purcell/exec-path-from-shell) and explicitly setting my [conda](https://github.com/necaris/conda.el) env. It works on my Linux laptop though.

**Comment by sakurawald** [comment]
I get the same error in Linux.

```
╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── INT ✘  base   at 06:40:48  ▓▒░─╮
╰─ pip --version                                                                                                                                                   ─╯
pip 24.0 from /opt/anaconda/lib/python3.12/site-packages/pip (python 3.12)

╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  base   at 06:40:52  ▓▒░─╮
╰─                                                                                                                                                                 ─╯

╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  base   at 06:40:53  ▓▒░─╮
╰─ pip3 --version                                                                                                                                                  ─╯
pip 24.0 from /opt/anaconda/lib/python3.12/site-packages/pip (python 3.12)

╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  base   at 06:40:57  ▓▒░─╮
╰─ which python                                                                                                                                                    ─╯
/opt/anaconda/bin/python

╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  base   at 06:41:20  ▓▒░─╮
╰─ which conda                                                                                                                                                     ─╯
conda () {
        \local cmd="${1-__missing__}"
        case "$cmd" in
                (activate | deactivate) __conda_activate "$@" ;;
                (install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
                        __conda_reactivate ;;
                (*) __conda_exe "$@" ;;
        esac
}

╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  base   at 06:41:22  ▓▒░─╮
╰─ which conda                                                                                                                                                     ─╯

╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── INT ✘  base   at 06:41:24  ▓▒░─╮
╰─ which pip                                                                                                                                                       ─╯
/opt/anaconda/bin/pip

╭─░▒▓    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ✔  base   at 06:41:30  ▓▒░─╮
╰─ which pip3                                                                                                                                                      ─╯
/opt/anaconda/bin/pip3
```

And 
```
╰─ pip3 install epc orjson sexpdata six setuptools paramiko rapidfuzz watchdog packaging                                                                           ─╯
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: epc in ./.local/lib/python3.12/site-packages (0.0.5)
Requirement already satisfied: orjson in ./.local/lib/python3.12/site-packages (3.10.15)
Requirement already satisfied: sexpdata in ./.local/lib/python3.12/site-packages (1.0.2)
Requirement already satisfied: six in /opt/anaconda/lib/python3.12/site-packages (1.16.0)
Requirement already satisfied: setuptools in /opt/anaconda/lib/python3.12/site-packages (69.5.1)
Requirement already satisfied: paramiko in ./.local/lib/python3.12/site-packages (3.5.1)
Requirement already satisfied: rapidfuzz in ./.local/lib/python3.12/site-packages (3.12.1)
Requirement already satisfied: watchdog in ./.local/lib/python3.12/site-packages (6.0.0)
Requirement already satisfied: packaging in /opt/anaconda/lib/python3.12/site-packages (23.2)
Requirement already satisfied: bcrypt>=3.2 in ./.local/lib/python3.12/site-packages (from paramiko) (4.3.0)
Requirement already satisfied: cryptography>=3.3 in /opt/anaconda/lib/python3.12/site-packages (from paramiko) (42.0.5)
Requirement already satisfied: pynacl>=1.5 in ./.local/lib/python3.12/site-packages (from paramiko) (1.5.0)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda/lib/python3.12/site-packages (from cryptography>=3.3->paramiko) (1.16.0)
Requirement already satisfied: pycparser in /opt/anaconda/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=3.3->paramiko) (2.21)
```

**Comment by sakurawald** [comment]
I found a solution:
1. Deactivate the `conda` environment using `conda deactivate`
2. Issue the `which python` should return the `/usr/bin/python`.
3. Issue `pip3 install epc orjson sexpdata six setuptools paramiko rapidfuzz watchdog packaging` to install the python packages *directly* into your machine python env.

**Comment by chookity-pokk** [comment]
> I found a solution:
> 
>     1. Deactivate the `conda` environment using `conda deactivate`
> 
>     2. Issue the `which python` should return the `/usr/bin/python`.
> 
>     3. Issue `pip3 install epc orjson sexpdata six setuptools paramiko rapidfuzz watchdog packaging` to install the python packages _directly_ into your machine python env.

That doesn't work for me. `which python` doesn't return anything and `which python3` returns my homebrew install of python. I then set my python interpreter [path as shown here](https://emacs.stackexchange.com/questions/33904/emacs-path-to-python-interpreter) to my base path which has all the installed packages but they aren't noticed. I still get the `epc package not found error`.

**Comment by sakurawald** [comment]
> > I found a solution:
> > ```
> > 1. Deactivate the `conda` environment using `conda deactivate`
> > 
> > 2. Issue the `which python` should return the `/usr/bin/python`.
> > 
> > 3. Issue `pip3 install epc orjson sexpdata six setuptools paramiko rapidfuzz watchdog packaging` to install the python packages _directly_ into your machine python env.
> > ```
> 
> That doesn't work for me. `which python` doesn't return anything and `which python3` returns my homebrew install of python. I then set my python interpreter [path as shown here](https://emacs.stackexchange.com/questions/33904/emacs-path-to-python-interpreter) to my base path which has all the installed packages but they aren't noticed. I still get the `epc package not found error`. Also though, launching `shell` and importing `epc` works just fine so this should be recognized by lsp-bridge.

I there is something wrong inside your terminal rc file.
If you are using `zsh`, you should include the `bash` config first. And thigns are similar.
